// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUDummyKeyForDevelopment123456789',
    authDomain: 'geochase-test.firebaseapp.com',
    projectId: 'geochase-test',
    storageBucket: 'geochase-test.appspot.com',
    messagingSenderId: '123456789',
    appId: '1:123456789:web:abcdef1234567890',
    databaseURL: 'https://geochase-test-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUDummyKeyForDevelopment123456789',
    appId: '1:123456789:android:abcdef1234567890',
    messagingSenderId: '123456789',
    projectId: 'flutter-app-taigogokko',
    storageBucket: 'flutter-app-taigogokko.appspot.com',
    databaseURL: 'https://geochase-test-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUDummyKeyForDevelopment123456789',
    appId: '1:123456789:ios:abcdef1234567890',
    messagingSenderId: '123456789',
    projectId: 'flutter-app-taigogokko',
    storageBucket: 'flutter-app-taigogokko.appspot.com',
    databaseURL: 'https://geochase-test-default-rtdb.firebaseio.com',
  );
}
